config: hzd_gl_policy
onboard:
  control:
    - pkg: g1_control
      params:
        hf_policy_name: "running_speed_symfix_29dof.pt"
        hf_repo_id: "zolkin/robot_rl"
        num_obs: 98
        num_actions: 29
        period: 0.43                   # s (half gait, from total_time=0.43 in policy YAML)
        ang_vel_scale: 1.0
        cmd_scale: [2., 2., 2.]
        qpos_scale: 1
        qvel_scale: 0.05
        action_scale: 0.25
        kps: [40.18, 40.18, 40.18, 99.10, 99.10, 40.18, 40.18, 40.18, 40.18, 99.10, 99.10,
              14.25, 14.25, 28.50, 28.50, 14.25, 14.25, 28.50, 28.50, 14.25, 14.25, 14.25, 14.25,
              14.25, 14.25, 14.25, 14.25, 14.25, 14.25]
        kds: [2.56, 2.56, 2.56, 6.31, 6.31, 2.56, 2.56, 2.56, 2.56, 6.31, 6.31,
              0.91, 0.91, 1.81, 1.81, 0.91, 0.91, 1.81, 1.81, 0.91, 0.91, 0.91, 0.91,
              0.91, 0.91, 0.91, 0.91, 0.91, 0.91]
        obs_type: "mlp"
        height_map_flag: False
        default_angles: [-0.25, -0.25, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.46, 0.46,
                         0.31, 0.31, -0.25, -0.25, 0.24, -0.24, 0.0, 0.0, 0.0, 0.0, 0.8, 0.8,
                         0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        default_angles_names: [
          "left_hip_pitch_joint", "right_hip_pitch_joint",
          "waist_yaw_joint",
          "left_hip_roll_joint", "right_hip_roll_joint",
          "waist_roll_joint",
          "left_hip_yaw_joint", "right_hip_yaw_joint",
          "waist_pitch_joint",
          "left_knee_joint", "right_knee_joint",
          "left_shoulder_pitch_joint", "right_shoulder_pitch_joint",
          "left_ankle_pitch_joint", "right_ankle_pitch_joint",
          "left_shoulder_roll_joint", "right_shoulder_roll_joint",
          "left_ankle_roll_joint", "right_ankle_roll_joint",
          "left_shoulder_yaw_joint", "right_shoulder_yaw_joint",
          "left_elbow_joint", "right_elbow_joint",
          "left_wrist_roll_joint", "right_wrist_roll_joint",
          "left_wrist_pitch_joint", "right_wrist_pitch_joint",
          "left_wrist_yaw_joint", "right_wrist_yaw_joint",
        ]
        log: true
        log_decimation: 1
        config_name: "hardware_config_running_29dof.yaml"
      executable: g1_controller
      publishers:
        - ros_parameter: pub_ctrl_setting
          topic: /obelisk/g1/low_level_control
          history_depth: 10
          callback_group: None
      subscribers:
        - ros_parameter: sub_est_setting
          topic: /obelisk/g1/est_state
          history_depth: 10
          callback_group: None
        - ros_parameter: sub_vel_cmd_setting
          topic: /obelisk/g1/high_level_ctrl
          history_depth: 10
          callback_group: None
        - ros_parameter: sub_joy_setting
          topic: /obelisk/g1/joy
      timers:
        - ros_parameter: timer_ctrl_setting
          timer_period_sec: 0.02
          callback_group: None

    - pkg: g1_control
      executable: high_level_control
      params:
        v_x_min: 0.0
        v_x_max: 3.0
        v_y_max: 0.4
        w_z_max: 0.5
        vel_increment: 0.1
        kp_yaw: 0.4
        kd_yaw: 0.0
        kp_x: 1.0
        kd_x: 0.1
        kp_y: 0.8
        kd_y: 0.3
        use_odom: True
        log_odom: True
        vel_increment_start: 1.2
      publishers:
        - ros_parameter: pub_ctrl_setting
          topic: /obelisk/g1/high_level_ctrl
          history_depth: 10
          callback_group: None
      subscribers:
        - ros_parameter: sub_joint_encoders
          topic: /obelisk/g1/joint_encoders
          msg_type: ObkJointEncoders
          history_depth: 10
          callback_group: None
        - ros_parameter: sub_est_setting
          topic: /obelisk/g1/joy
          history_depth: 10
          callback_group: None
        - ros_parameter: sub_odom_setting
          topic: /Odometry
          history_depth: 10
          callback_group: None
        - ros_parameter: sub_vel_cmd_setting
          topic: /obelisk/g1/unitree_high_level_ctrl
          history_depth: 10
          callback_group: None
      timers:
        - ros_parameter: timer_ctrl_setting
          timer_period_sec: 0.05
          callback_group: None

    - pkg: obelisk_unitree_cpp
      executable: obelisk_unitree_joystick
      params:
        v_x_max: 1.5
        v_y_max: 1.0
        w_z_max: 0.5
      publishers:
        - ros_parameter: pub_exec_fsm_setting
          topic: /obelisk/g1/exec_fsm
          history_depth: 10
          callback_group: None
        - ros_parameter: pub_ctrl_setting
          topic: /obelisk/g1/unitree_high_level_ctrl
          history_depth: 10
          callback_group: None
      subscribers:
        - ros_parameter: sub_est_setting
          topic: /obelisk/g1/joy
      timers:
        - ros_parameter: timer_ctrl_setting
          timer_period_sec: 100
          callback_group: None

  estimation:
    - pkg: g1_control
      executable: g1_estimator
      publishers:
        - ros_parameter: pub_est_setting
          topic: /obelisk/g1/est_state
          msg_type: EstimatedState
          history_depth: 10
          callback_group: None
      subscribers:
        - ros_parameter: sub_joint_encoders
          topic: /obelisk/g1/joint_encoders
          msg_type: ObkJointEncoders
          history_depth: 10
          callback_group: None
        - ros_parameter: sub_pelvis_imu
          topic: /obelisk/g1/pelvis_imu
          msg_type: ObkIMU
          history_depth: 10
          callback_group: None
      timers:
        - ros_parameter: timer_est_setting
          timer_period_sec: 0.001
          callback_group: None

  robot:
    - is_simulated: False
      pkg: obelisk_unitree_cpp
      executable: obelisk_unitree_g1_hardware
      params:
        ic_keyframe: standing
        network_interface_name: enx6c1ff7207b57
        default_kp: [
          40.18, 40.18, 40.18,    # L hip, R hip, waist_yaw
          99.10, 99.10, 40.18,    # L hip_roll, R hip_roll, waist_roll
          40.18, 40.18, 40.18,    # L hip_yaw, R hip_yaw, waist_pitch
          99.10, 99.10,            # L knee, R knee
          14.25, 14.25,            # L shoulder_pitch, R shoulder_pitch
          28.50, 28.50,            # L ankle_pitch, R ankle_pitch
          14.25, 14.25,            # L shoulder_roll, R shoulder_roll
          28.50, 28.50,            # L ankle_roll, R ankle_roll
          14.25, 14.25,            # L shoulder_yaw, R shoulder_yaw
          14.25, 14.25,            # L elbow, R elbow
          14.25, 14.25,            # L wrist_roll, R wrist_roll
          14.25, 14.25,            # L wrist_pitch, R wrist_pitch
          14.25, 14.25,            # L wrist_yaw, R wrist_yaw
        ]
        default_kd: [
          2.56, 2.56, 2.56,
          6.31, 6.31, 2.56,
          2.56, 2.56, 2.56,
          6.31, 6.31,
          0.91, 0.91,
          1.81, 1.81,
          0.91, 0.91,
          1.81, 1.81,
          0.91, 0.91,
          0.91, 0.91,
          0.91, 0.91,
          0.91, 0.91,
          0.91, 0.91,
        ]
        user_pose: [-0.25, -0.25, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.46, 0.46,
                     0.31, 0.31, -0.25, -0.25, 0.24, -0.24, 0.0, 0.0, 0.0, 0.0, 0.8, 0.8,
                     0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        logging: True
      publishers:
        - ros_parameter: pub_true_sim_state_setting
          topic: /obelisk/g1/true_sim_state
          history_depth: 10
          callback_group: None
        - ros_parameter: pub_sensor_setting
          topic: /obelisk/g1/joint_encoders
          history_depth: 10
        - ros_parameter: pub_imu_setting
          topic: /obelisk/g1/pelvis_imu
          history_depth: 10
        - ros_parameter: pub_odom_setting
          topic: /obelisk/g1/odom
          history_depth: 10
      timers:
        - ros_parameter: timer_true_sim_state_setting
          history_depth: 10
          timer_period_sec: 0.002
          callback_group: None
      subscribers:
        - ros_parameter: sub_ctrl_setting
          topic: /obelisk/g1/low_level_control
          history_depth: 10
          callback_group: None
        - ros_parameter: sub_fsm_setting
          topic: /obelisk/g1/exec_fsm
          history_depth: 10
          callback_group: None
        - ros_parameter: sub_high_level_ctrl_setting
          topic: /obelisk/g1/high_level_ctrl
          history_depth: 10
          callback_group: None

  viz:
    on: False
    viz_tool: foxglove
    viz_nodes:
      - pkg: obelisk_viz_cpp
        executable: default_robot_viz
        robot_pkg: g1_model
        urdf: g1_hand.urdf
        robot_topic: robot_description
        subscribers:
          - ros_parameter: sub_viz_est_setting
            topic: /obelisk/g1/est_state
            history_depth: 10
            callback_group: None
            non_obelisk: False
        publishers:
          - ros_parameter: pub_viz_joint_setting
            topic: joint_states
            history_depth: 10
            callback_group: None
        timers:
          - ros_parameter: timer_viz_joint_setting
            timer_period_sec: 0.01
            callback_group: None

  joystick:
    on: True
    pub_topic: /obelisk/g1/joy
    sub_topic: /obelisk/g1/joy_feedback
